### PR TITLE
Add more messaging while running, Improve the code structure for people new to coding

### PR DESCRIPTION
**Pull request by alexDrinkwater**
Sample console output with this PR:

```
Welcome to the MIQ Booking Assistance!
A new browser window should appear. Please navigate to "Secure your allocation" page.
Checked MIQ: 36 times, last checked at: 7/9/2021, 3:33:05 PM
```

### CODE REVIEW

**Comment by jvolker** [comment]
Thanks for your work. I like the idea to make it more approachable for people new to coding and the console output. I'm going to try to look at this more closely, hopefully sometime next week.

**Comment by jvolker** [comment]
@alexDrinkwater, this looks good. I'm going to merge it even though I didn't have a chance to check if the beeping is still working. Could you please confirm that it did work for you?

**Comment by alexDrinkwater** [comment]
@jvolker I didn't leave it running long enough to confirm the beep, but I did move the beep() call into the else of the ```if (found){...}``` code block to test the function still worked in the new scope.

**Comment by rtperkins0** [comment]
@jvolker I've been using this version for a couple of days, the 'Beep' does work in this version when an open day is found.

**Comment by jvolker** [comment]
Thanks, @alexDrinkwater for your work and reply and @rtperkins0 for confirming this! Merged this now.

**Pull request merged**
