### PR TITLE
added functionality for multiple rooms of the same type

### PR DESCRIPTION
**Pull request by Yokai**
created branch on my fork called changeRoomTypes

Now allows for 2 rooms and can have the same type of room (Twin share or Double) for both rooms
Allows for still selecting only 1 room and choosing either Twin share or Double in that room

### CODE REVIEW

**Comment by jvolker** [comment]
Thanks, @Yokai, for your work. This looks very useful. Unfortunately, I don't have a lot of time right now to properly review it. If anyone else has the time to test and review the code and give feedback here, it would be awesome.

And thanks, @bmcfetty, for checking this so quickly. @Yokai Before the PR can be merged, the credentials need to be removed. I've never removed data from a PR before, but maybe you can find more info here: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by Sandeep77R** [comment]
thanks so much for this! works well - only very slight issue is that it scrolls back up to the top, so need to scroll back down to the calendar - but it works otherwise.

**Comment by jvolker** [comment]
@Yokai Thanks again for your work. I just checked the code, and it seems to work for me too. 👍 

However, I still don't want to merge this as your credentials are in there. 

My understanding is that it's not possible to remove a few lines of changes from a PR. So I think you would have to follow the procedure described in the link above or create a new PR without the credentials. We can then ask Github to delete this PR entirely.
As an alternative, I might be able to remove your credentials, rebase the code and merge it. But my feeling is that it would overwrite your authorship of the commit. 

I'm not sure what to do as I want to merge the changes and respect your authorship. What do you think?

If you decide to start a new PR, it might be best to do this after I dealt with https://github.com/jvolker/miq-nz-booking-tools/pull/6 as this restructures the code a little. 

Would you please let me know if you prefer me to merge it without your remaining authorship?

**Comment by jvolker** [comment]
Hey everyone, what are your opinions on this? Should I add the changes by losing @Yokai's authorship or wait?

The changes would open the tool up to people with multi-room requirements. I would like to add support for all the options of the form.

**Comment by alexDrinkwater** [comment]
This is no longer needed because the MIQ website has separated the room requirements in a separate step before selecting the date.

**Comment by Yokai** [comment]
Thanks for that - and thanks for the creds reminder - I must not do things at 1am.

**Pull request closed without merging**
