### PR TITLE
Add the ability to search for specific days, months or any date.

### PR DESCRIPTION
**Pull request by alexDrinkwater**

### CODE REVIEW

**Comment by alexDrinkwater** [comment]
image

**Comment by alexDrinkwater** [comment]
image

**Comment by alexDrinkwater** [comment]
@jvolker I also added the ability to put test dates in using the `testDates` array. This injects the dates into the flatpickr.

**Comment by jvolker** [comment]
@alexDrinkwater again, thank you so much for all your hard work. I'm very glad you are continuously sending pull requests. Now, this weekend I won't have any time to work on this project. At the same time, I don't want to slow you down or stop your momentum. So please go ahead with what you think is best for the majority of people. I just made you a collaborator on the project. 

Regarding this PR I didn't have any time to look into the code. What you are describing in the comments sound good. Most people seemed to ask for multiple months (larger ranges) rather than specific dates. So I think most sense to me would make the option to scan a range of dates from/to. Is it still going to be possible to search across a whole month?

> @jvolker I also added the ability to put test dates in using the testDates array. This injects the dates into the flatpickr.

Awesome!

I can have a look at this PR next week. But feel free to merge if you think it's ready and doesn't decrease functionality. Maybe someone else might do some reviewing and exchange ideas!?

Thanks again. And don't burn the house … ;)

**Comment by alexDrinkwater** [comment]
@jvolker Thanks for making me a contributor. Take a look at the screen shots above for what types of things you can specify. Based on the dates array being = ['2021-08-12', '2021-08-13', '2021-09'] the program will search for August 12th 2021, August 13th 2021, and all of September 2021. If any get found it will switch the flatpickr to the first month of the found date, start beeping and stop the loop. Alternatively, the user can select 'Find any date', in this mode it will search for any available dates and move to the month of the first one found.

**Comment by lostminty** [comment]
Hey,

I've been using this version of the app and it has twice crashed from an unhandled rejection exception or something like that. I'll post the traceback when I get home.

I modified the beep function to send a message to my phone using push safer API. Haven't done any tests of this method but it's in a try/catch

**Comment by nedmi** [comment]
HI Alex Drinkwater, Great to see  you have made the  change for specific dates 
 I have 9.0 I would like to use the specific day feature it is not on my screen how do I update my version how do I add the feature? 
thanks a tonne Nedmi

**Comment by alexDrinkwater** [comment]
@lostminty Were you able to find the exception you were experiencing?

**Comment by alexDrinkwater** [comment]
@nedmi This change is still pending. Looks like @lostminty has found an issue with it.

**Comment by lostminty** [comment]
> @lostminty Were you able to find the exception you were experiencing?

Hi again

The website itself displayed connection reset

The traceback was an unhandled promise for selecting in the section which selects the disability room question from memory.

It's quite possible it was an issue with WiFi at the place I was running the laptop I've been using. I noticed the wifi drop on my phone fairly regularly.

**Comment by nobla** [comment]
How do I download this version of the App please?

**Comment by nedmi** [comment]
HI Alex and Volker, Thanks my miss I hope it may come along so will  continue to check.
You both are doing so much I hope to get a booking confirmed and will celebrate your collective efforts and hopefully find a way to show my gratitude cheers Nedmi

**Comment by alexDrinkwater** [comment]
fixes #39, #35, #28

**Comment by alexDrinkwater** [comment]
fixes #8

**Comment by jvolker** [comment]
Great work, @alexDrinkwater! Thanks a lot.

I just added Mac binaries to the release.

**Comment by nedmi** [comment]
HI Jeremias, I am glad to see  that Alex has completed the search for specific days, months or any date( way to go Alex) I do not see the option when I am on  MIQ booking assistance page on an option to pick a month a room double or twin and  accessibility option.
do I need  to upload and update to my 9.0 version? if so how do I upload the latest version 
thanks for the support  cheers Nedmi

**Comment by alexDrinkwater** [comment]
@nedmi Please download the 0.10.0 release from here: https://github.com/jvolker/miq-nz-booking-tools/releases

**Pull request merged**
